# Generated by Django 4.0.6 on 2022-08-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(related_name='likers', to='network.post'),
        ),
    ]
